// #define DEBUG_DATA
// #define DEBUG_COMMISSIONING_DATA
// #define DEBUG_ENCRYPTION
// #define DEBUG_REGISTER_CONFIG

/** Manufacturer data */
#define ENOCEAN_MANUFACTURER_ID 0x03DA
#define PMT215B_STATIC_SOURCE_ADDRESS_FIRST_BYTE 0xE2
#define PMT215B_STATIC_SOURCE_ADDRESS_SECOND_BYTE 0x15

#define LONG_PRESS_INTERVAL_MS          1000
